reorproject/reor

.github/workflows/build.yml
electron/main/Store/storeHandlers.ts
electron/main/llm/llmSessionHandlers.ts
electron/main/llm/models/LlamaCpp.ts
src/components/Chat/Chat.tsx
src/functions/error.ts

Error progagation chat

---

electron-builder.json5
package.json

#12 
Fixes issue with not finding metal

ass in necessary asar packs for finding metal

---

src/components/Settings/NewLocalModel.tsx

drop gguf file type req in dialog

---

electron/main/Files/Filesystem.ts
electron/main/Files/registerFilesHandler.ts
electron/main/database/TableHelperFunctions.ts
electron/main/index.ts

Filter imports by markdown

---

src/components/Settings/OpenAISetup.tsx

Adding the new OpenAI models to the list.

Add OpenAI models gpt-3.5-turbo-0125 and gpt-4-0125-preview

---

src/components/FileEditorContainer.tsx
src/components/TitleBar.tsx

Add fill icon for related notes tab

add fill when related notes tab is opened

---

.github/workflows/build.yml
.github/workflows/release.yml
electron/main/database/LanceTableWrapper.ts
src/components/Similarity/SimilarFilesSidebar.tsx

fix lancedb recordbatch problem

---

electron/main/Store/storeConfig.ts
electron/main/Store/storeHandlers.ts
electron/main/database/TableHelperFunctions.ts
electron/main/llm/Types.ts
electron/main/llm/llmSessionHandlers.ts
electron/main/llm/models/LlamaCpp.ts
electron/main/llm/models/OpenAI.ts
electron/preload/index.ts
package.json
src/components/Settings/HardwareSettings.tsx
src/components/Settings/RagSettings.tsx
src/components/Settings/Settings.tsx

Gpu support (nvidia & amd)

---

README.md
electron/main/Store/storeHandlers.ts
electron/preload/index.ts
src/components/Generic/Select.tsx
src/components/Settings/LLMSettings.tsx

I added the Functions and the Button to delete the choosen LLM. I also updated the README with some information about the file structure.

Folder Structure & delete btn

---

src/components/File/NewDirectory.tsx
src/components/File/NewNote.tsx
src/functions/strings.ts

Change Directory and Note name restriction rules

---

src/components/Chat/Chat-Prompts.tsx
src/components/Chat/Chat.tsx

Adds the ability to:
1. ask specific file
2. Autofill prompts
3. additional animation and handling to make things clearer for users
https://github.com/reorproject/reor/assets/58682208/dd260366-9a8a-4c08-8ed2-bfa06566dc2d

adds dynamic chat prompts and dropdown render with prompt selection

---

.containerignore
.gitignore
Containerfile
package-lock.json

- **Add package-lock.json to source control**
- **Add Containerfile**
The resulting images are 5GB, but I'm not familiar enough with Electron to get them smaller without considerable effort. It's a start, at least.
Closes #46

Add Containerfile and package-lock.json

---

electron/main/database/LanceTableWrapper.ts
src/components/Chat/Chat-Prompts.tsx
src/components/Chat/Chat.tsx
src/components/FileEditorContainer.tsx

Adding the component for now, to be used later with the ask-file format
https://github.com/reorproject/reor/assets/58682208/a958d470-458f-4377-a4e0-25f3e3912de0

add chat with particular note, and prompt template

---

README.md
package-lock.json
src/components/Chat/Chat-Prompts.tsx
src/components/Chat/Chat.tsx
src/styles/global.css

This PR adds:
1. more chat prompts
2. better margin padding
3. Toast error when file is not actively selected in the ask file mode, alongside with automatic dismissal
4. also added a discord CTA in the readme

add toast error and automatic dismiss

---

src/components/File/Todo/ListItem.tsx
src/styles/global.css

This PR fixes a OL bug where numbered lists were turning into UL

fix ordered list and allow ul/ol to nest between each other

---

electron/main/Files/Filesystem.ts
electron/main/Files/Types.ts
electron/main/Files/registerFilesHandler.ts
electron/main/database/TableHelperFunctions.ts
electron/preload/index.ts
src/components/File/MdxEditor.tsx
src/components/File/MilkdownEditor.tsx
src/components/FileEditorContainer.tsx

Use file modified time to decide whether to update db

---

src/components/Chat/Chat.tsx
src/components/File/FileSidebar.tsx
src/components/Sidebars/IconsSidebar.tsx
src/components/Similarity/SimilarFilesSidebar.tsx
src/components/TitleBar.tsx

New users won't know what any of these icons do.

Add Hover Hints to Icons

---

electron/main/database/LanceTableWrapper.ts
electron/main/database/TableHelperFunctions.ts

speedup 4x in checking which files to add back to table because now we don't process content nor the vectors in computing what is missing from the table

Process less fields in table to check what to re-index

---

.prettierrc
electron/main/Files/registerFilesHandler.ts
electron/main/Store/storeHandlers.ts
electron/main/index.ts
electron/main/windowManager.ts
electron/preload/index.ts
src/components/File/TipTapEditor.tsx
src/components/File/hooks/use-file-by-filepath.ts
src/components/FileEditorContainer.tsx

- File content is no longer passed around as a hook.
- editor is initialized in hook file
- Close window no longer tries to block close

Extend custom hooks

---

.prettierrc
electron/main/Files/registerFilesHandler.ts
electron/main/Store/storeHandlers.ts
electron/main/database/dbSessionHandlers.ts
electron/main/index.ts
electron/main/windowManager.ts
electron/preload/index.ts
src/components/File/FileSidebar.tsx
src/components/File/TipTapEditor.tsx
src/components/File/hooks/use-file-by-filepath.ts
src/components/FileEditorContainer.tsx
src/components/Similarity/SimilarFilesSidebar.tsx

This PR adds:
1. cascading delete of vectors upon deleting file
2. Ability to delete file while in file
3. Custom data management hook so that we split out UI render from data management
4. Save file on close

add custom hooks and refactor delete functionality for editor

---

electron/main/Files/registerFilesHandler.ts
electron/main/Store/storeHandlers.ts
electron/main/database/dbSessionHandlers.ts
electron/main/index.ts
electron/main/windowManager.ts

- This makes managing windows much clearer 
- And helps fix the bug when losing the directory on window close:
https://github.com/reorproject/reor/assets/17236551/9e1b8332-19b8-4a5d-aa32-73296fef27eb

make windows manager a class

---

electron/main/index.ts
package-lock.json
src/App.tsx
src/components/Chat/Chat.tsx
src/components/FileEditorContainer.tsx
src/components/TitleBar.tsx

- make windows system buttons match title bar
- darken title bar & chat input div
- #143

Windows title bar

---

src/components/File/FileSideBar/FileHistoryBar.tsx
src/components/File/FileSideBar/index.tsx
src/components/FileEditorContainer.tsx
src/components/TitleBar.tsx
src/styles/history.scss

Fixes #50
Currently, it seems to be working smoothly. We can test it and then roll it out. The only issue at the moment is that the history gets cleared when it's rendered by an upper layer. This will be addressed later by adding the persistence storage feature.

Browser-like back and forth buttons

---

.gitignore
electron/main/llm/models/Ollama.ts
package-lock.json
package.json
scripts/downloadOllama.js
src/components/Settings/ExtraModals/NewOllamaModel.tsx

- No longer track ollama binary
- Script to download ollama
- Bump ollama version to test fix for #162

add downloadOllama script

---

package.json
src/components/File/hooks/use-file-by-filepath.ts

Aiming to fix #77 
- Await save on file change
- Introduce state to mange file paths being changed

await save and add state to deal with file path changes

---

electron/main/Files/registerFilesHandler.ts
electron/main/database/dbSessionHandlers.ts
electron/main/llm/Types.ts
electron/main/llm/llmSessionHandlers.ts
electron/main/llm/models/Ollama.ts
electron/main/llm/models/OpenAI.ts
electron/preload/index.ts
src/components/Chat/Chat.tsx
src/components/Chat/ChatAction.tsx

output: 
Process:
https://github.com/reorproject/reor/assets/58682208/2199c2bc-1e43-4207-aad3-981eeec2a747

add persistence to JSON file for flashcards in hidden directory

---

src/components/Chat/Chat.tsx
src/components/Flashcard/index.ts

Just cleanly separating the flashcard specific parsing logic out from Chat. Doesn't do anything except for prepping for flashcard UI and defining the types for render later

add flashcard directory (prep to display flashcards next)

---

electron/main/Store/storeHandlers.ts
electron/main/index.ts
electron/main/llm/llmSessionHandlers.ts
electron/main/windowManager.ts
electron/preload/index.ts
src/App.tsx
src/components/Chat/Chat.tsx
src/components/Chat/CustomLinkMarkdown.tsx
src/components/File/FileSideBar/FileItem.tsx
src/components/File/NewDirectory.tsx
src/components/File/NewNote.tsx
src/components/File/hooks/use-file-by-filepath.ts
src/components/Settings/DirectorySelector.tsx
src/components/Settings/EmbeddingSettings.tsx
src/components/Settings/InitialEmbeddingSettings.tsx
src/components/Settings/LLMSettings.tsx
src/components/Settings/RagSettings.tsx
src/components/Settings/TextGenerationSettings.tsx

Make every ipc call use invoke and handle

---

src/components/File/hooks/use-file-by-filepath.ts

- basically uses richtextlink extension from doist

support links + markdown linking syntax

---

src/components/File/DBResultPreview.tsx

Added Filename of chunk that appears in Related Notes. #189

Added FileName in chunk for Related Notes.

---

electron/main/Store/storeConfig.ts
electron/main/llm/Types.ts
electron/main/llm/llmConfig.ts
electron/main/llm/llmSessionHandlers.ts
electron/main/llm/models/Anthropic.ts
package-lock.json
package.json
src/components/Chat/Chat.tsx
src/components/Generic/Select.tsx
src/components/Settings/ExtraModals/CloudLLMSetup.tsx
src/components/Settings/LLMSettings.tsx

I wanted to try reor with anthropic LLMs so I added them as an alternative to the openAI ones. I've made a fair bit of changes and some to the types and interfaces, hope these don't break anything!
Closes #188 
- On a separate note, while I'm not familiar with tools like langchain and llamaIndex, what are our thoughts on integrating with these kind of tools, it seems like they provide quite of a lot of basic functionalities?

Add anthropic LLMs

---

electron/main/RAG/Chunking.ts
electron/main/Store/storeConfig.ts
electron/main/Store/storeHandlers.ts
electron/main/Store/storeMigrator.ts
electron/preload/index.ts
src/components/Settings/ChunkSizeSettings.tsx
src/components/Settings/Settings.tsx

https://github.com/reorproject/reor/issues/193

Support changing chunk size & chunking scheme in settings #193

---

src/components/Settings/ExtraModals/NewOllamaModel.tsx

Send toast notifications for model download completion/failure

---

src/components/Settings/Settings.tsx

mentioned in https://github.com/reorproject/reor/issues/258#issuecomment-2143844970

fix: moved `Chunk Size` inside `RAG` in settings

---

package-lock.json
package.json
src/components/File/hooks/use-file-by-filepath.ts

Added LaTex Support. Closes #271 
View:
Need to add:
- Need to configure to add support for matrices.

Latex support

---

electron/main/Store/storeConfig.ts
electron/main/Store/storeHandlers.ts
electron/main/Store/storeMigrator.ts
electron/preload/index.ts
src/components/File/hooks/use-file-by-filepath.ts
src/components/Settings/GeneralSettings.tsx
src/components/Settings/Settings.tsx

https://github.com/reorproject/reor/issues/258

Spell Check

---

src/components/File/FileSideBar/FileItem.tsx
src/components/File/FileSideBar/index.tsx

https://github.com/reorproject/reor/issues/278

fix: drag notes from folder to the root(non-folder) by placing it in blank space

---

electron/preload/index.ts

- Remove pesky code duplication in preload

initial work to cleanup preload

---

src/components/File/FileSideBar/index.tsx
src/components/FileEditorContainer.tsx
src/components/Sidebars/MainSidebar.tsx
src/components/Similarity/SimilarFilesSidebar.tsx
src/styles/global.css

- Fixes the scrolling issues in the editor

Fix height issue

---

.eslintrc.js
electron/main/common/network.ts
electron/main/common/windowManager.ts
electron/main/electron-store/ipcHandlers.ts
electron/main/electron-store/storeConfig.ts
electron/main/electron-store/storeSchemaMigrator.ts
electron/main/filesystem/ipcHandlers.ts
electron/main/llm/llmConfig.ts
electron/main/llm/models/Anthropic.ts
electron/main/vector-database/ipcHandlers.ts
package.json
src/App.tsx
src/components/Chat/AddContextFiltersModal.tsx
src/components/Chat/Chat.tsx
src/components/Chat/ChatsSidebar.tsx
src/components/Chat/chatUtils.ts
src/components/Common/TitleBar.tsx
src/components/File/DBResultPreview.tsx
src/components/File/FileSideBar/FileHistoryBar.tsx
src/components/File/RenameNote.tsx
src/components/File/hooks/use-file-by-filepath.ts
src/components/Settings/AnalyticsSettings.tsx
src/components/Settings/GeneralSections.tsx
src/components/Settings/GeneralSettings.tsx
src/components/Settings/TextGenerationSettings.tsx
src/components/Sidebars/SimilarFilesSidebar.tsx
src/styles/global.css

Revert "Stylistic precommit settings"

---

electron/main/electron-utils/ipcHandlers.ts

Fixed the issue as reported by the users here [https://github.com/reorproject/reor/issues/323](url).

Fixed delete chat issue

---

src/components/Chat/Chat.tsx
src/components/MainPage.tsx

fix #343 
/claim #343
https://github.com/user-attachments/assets/a45cfca0-099a-4628-b857-4fe7fe809fa7

Add copy and new note on chat

---

src/components/Editor/EditorManager.tsx
src/components/Writing-Assistant/WritingAssistantFloatingMenu.tsx

fix #349 
/claim #349 
https://github.com/user-attachments/assets/82033104-f7ce-4a5e-9a5c-2e159c5dd2b9

feat: trigger writing assistant without highlighting text completed

---

package-lock.json
src/components/File/NewDirectory.tsx
src/components/File/NewNote.tsx
src/components/File/RenameDirectory.tsx
src/components/File/RenameNote.tsx
src/utils/strings.ts

Fix new file bug

---

electron/main/index.ts
electron/main/llm/llmConfig.ts
electron/preload/index.ts
src/components/Chat/ChatMessages.tsx
src/components/Settings/LLMSettings/DefaultLLMSelector.tsx
src/components/Settings/LLMSettings/InitialSetupLLMSettings.tsx
src/components/Settings/LLMSettings/LLMSettingsContent.tsx
src/components/Settings/LLMSettings/NormalLLMSettings.tsx

/claim #381
Fixes : #381
After adding the changes , now the home layout looks like below

Added Send Button and Dropdown in Chatbot Homelayout

---

package-lock.json
package.json
src/components/Editor/HighlightExtension.tsx
src/components/WritingAssistant/WritingAssistant.tsx
src/components/ui/popover.tsx

Fixes #402 
/claim #402
Now We can see the AI Assistant in all the cases as shown below in video 
[screen-capture.webm](https://github.com/user-attachments/assets/1a585863-806a-4fb4-8757-a58d186666c0)

Feat : AI Assistant Options Partially Hidden or Not Visible While Scrolling down the page and Selecting Text

---

package-lock.json
package.json
src/components/Chat/ChatSidebar.tsx
src/components/Chat/MessageComponents/ChatSources.tsx
src/components/File/DBResultPreview.tsx
src/components/Settings/LLMSettings/DefaultLLMSelector.tsx
src/components/Sidebars/SearchComponent.tsx
src/lib/animations.tsx
src/lib/db.ts
tailwind.config.js

Allow users to choose between semantic search and keyword search for flexibility.

feat: hybrid search
