electron-builder.json5

While packaging reor for homebrew-cask, I found the appID is wrong, thus fixing it.
relates to https://github.com/Homebrew/homebrew-cask/pull/167053

fix electron-builder appID

---

electron/main/Files/Types.ts
electron/main/Files/registerFilesHandler.ts
electron/main/Prompts/Prompts.ts
electron/main/database/dbSessionHandlers.ts
electron/preload/index.ts
src/components/Chat/Chat-Prompts.tsx
src/components/Chat/Chat.tsx

This PR adds:
- AugmentPrompt with file handler
- Toast errors if a file is not yet selected and if the context is too large
- Removes previous augment prompt context filter and separate the cases
Example warning message (edited so that it doesn't block generating the output, but still not ideal yet)

add files based content prompting

---

package-lock.json
package.json
src/components/File/hooks/use-file-by-filepath.ts

- Fixes issue with checkboxes and code blocks being lost after being written to disk and then reopened.
- This now uses tiptap-markdown to deal with markdown in tiptap

switch to using titpap markdown extension

---

electron/main/Store/storeHandlers.ts
electron/main/index.ts
electron/main/llm/llmSessionHandlers.ts
electron/main/llm/models/Ollama.ts
electron/main/windowManager.ts
src/App.tsx
src/components/Settings/ExtraModals/NewOllamaModel.tsx

- Manage ollama server in steps (same implementation as chatd):
1. Ping to check if ollama is running
2. Attempt to start if "ollama" alias present
3. Start ollama via the binary
- Add ollama stop call and call stop on before-quit
Other improvements:
- Createwindow function now in windowManager
- registerHandler functions run in main like other handlers - to ensure they don't run twice and error (when a window is closed and then reopened)
Remaining todos for another PR:
- Manage multiple downloads at once via sending modelname via ipc event send
- Also solve the flickering at the end of a download between 0 and 100%
- Update wording on new local model page

Improve ollama server setup reliability

---

src/components/File/NewNote.tsx

Fixes #168
- Limit filename length to a maximum of 255 characters.
- Automatically add filename as the document title.

Auto Title Feature

---

electron/preload/index.ts
src/components/Chat/Chat.tsx
src/components/File/FileSideBar/hooks/use-file-info-tree.tsx
src/components/File/hooks/use-file-by-filepath.ts
src/components/Settings/ExtraModals/NewOllamaModel.tsx
src/components/Similarity/SimilarFilesSidebar.tsx

The IPC communication process causes functions sent across to be deserialized and serialized, hence the listeners are mutating reference and cannot be removed from the frontend since the function instances are different. 
By making the receive command return the remove event listener function, we are able to properly maintain the reference to the function that was being added to the channel and thus remove it cleanly. Now we dont need the `active` or not hack in useEffect.

allow frontend to properly remove event listener on useffect unmount

---

electron/main/Files/registerFilesHandler.ts
electron/main/Prompts/Prompts.ts
electron/main/database/dbSessionHandlerTypes.ts
electron/main/database/dbSessionHandlers.ts
electron/preload/index.ts
package-lock.json
src/components/Chat/Chat.tsx

Generally got it working to output the right format pretty reliably, but the RAG pipeline still isnt picking up on:
1. The name of the note(we really need to add this, the results here use the entirely wrong note for it), and hybrid text search
2. It isn't aware of alternative concepts related to the same question I am making
it is outside of the scope of this PR, but I would probably work on hybrid text search next
Future work for these custom prompts require:
1. Separate steps to generate the prompt
2. Emphasize/select previous output when generating next prompt (maybe some sort of a prior filter or selector component)
3. Allow it to generate intermediate output, and conditionally take in previous context
4. Some warning for prompt exceeding token limits (now that we can have this idea …

add flashcard custom prompt

---

src/components/File/NewNote.tsx
src/components/File/hooks/use-file-by-filepath.ts
src/components/FileEditorContainer.tsx
src/components/Sidebars/IconsSidebar.tsx

Given that we write to disk and index editor content at different intervals, that requires some state to know when we need to index the content to the database:
- PR introduces ```needToIndexEditorContent``` state variable
- Makes newnote component use ```openRelativePath``` function so that we don't need to duplicate logic in different files

introduce state to deal with whether current editor content has been indexed

---

electron/main/index.ts
package-lock.json
package.json
src/components/Chat/AddContextFiltersModal.tsx
src/components/Chat/Chat.tsx
src/components/Chat/ChatInput.tsx
src/components/Editor/FilesSuggestionsDisplay.tsx
src/components/FileEditorContainer.tsx
src/components/Flashcard/FlashcardCreateModal.tsx
src/components/Flashcard/FlashcardMenuModal.tsx
src/components/Generic/SearchBarWithFilesSuggestion.tsx
src/components/Sidebars/MainSidebar.tsx
src/components/Similarity/SimilarFilesSidebar.tsx

This PR adds:
1. Ability to add file filters and have them show up in the sidebar
2. Have the file filters show up as list in the modal
3. Resetting chat history and context when new chat is created
4. Updated Chat history colors to be less loud
5. Display files selected as context on the side bar to allow users to know that the file was successfully attached
Further work:
1. Doesnt handle the situation where files are out of context because its too long
2. Doesn't handle deleting files in the modal, but you can reset the chat for now by either leaving chat mode or hitting the `+ New chat` button

second try at adding files filters

---

electron/main/Store/storeConfig.ts
electron/main/Store/storeHandlers.ts
electron/main/Store/storeMigrator.ts
electron/preload/index.ts
index.html
package-lock.json
package.json
src/App.tsx
src/components/Chat/Chat.tsx
src/components/Editor/BacklinkSuggestionsDisplay.tsx
src/components/File/hooks/use-file-by-filepath.ts
src/components/FileEditorContainer.tsx
src/components/Flashcard/FlashcardCreateModal.tsx
src/components/Flashcard/FlashcardMenuModal.tsx
src/components/Settings/AnalyticsSettings.tsx
src/components/Settings/Settings.tsx
src/components/Sidebars/MainSidebar.tsx

Fairly simple, non-intrusive counting analytics using posthog.

add posthog to system

---

electron/main/Files/registerFilesHandler.ts

From https://github.com/reorproject/reor/issues/174. Users can now rename directories that contain file contents. Does so by:
- Checking if user is running in windows environment,
- Saving all watcher paths
- Closing all watcher objects
- Renaming file
- Re-opening all watcher objects

Fixed operation not permitted when renaming directory with children in windows

---

electron/main/index.ts

As a first-time user of reor, I accidentally deleted a whole folder of important documents. To prevent this from happening to other users, I have added a confirmation dialog that prompts the user to confirm their action before a file is deleted.
---
Can probably add a checkbox to the delete confirmation dialog similar to the one in Obsidian.
checkboxLabel: "Don't ask again",
checkboxChecked: false,

Added a confirmation dialog to prevent accidental file deletions

---

electron/main/Store/storeHandlers.ts
electron/main/index.ts
electron/preload/index.ts
src/components/Chat/Chat.tsx
src/components/Chat/ChatsSidebar.tsx
src/components/Chat/hooks/use-chat-history.ts
src/components/FileEditorContainer.tsx
src/components/Sidebars/MainSidebar.tsx

Right now there is no way to delete chat histories. The following PR allows users to:
- Permanently remove a chat in their history
- If they are currently viewing the chat and delete it, then setViewChat to false.
- If they are viewing a chat and delete another chat, then continue viewing the current.
Closes #245

Allow users to delete their chat histories

---

electron/main/index.ts
electron/preload/index.ts
src/components/File/FileSideBar/FileItem.tsx
src/components/File/FileSideBar/index.tsx
src/components/File/NewDirectory.tsx
src/components/File/NewNote.tsx
src/components/Sidebars/IconsSidebar.tsx

From #284 
Added ability to:
- Create new Note / Directores when rightclicking a directory
- New note / directoy is a child of this directory
- Right clicking empty file sidebar creates new context menu for creating file or directory
Possible Changes:
- Inside index.tsx, is there a way to check if this file is a directory or not without using node.js `fs`? Ideally each file object would create a field that states if this is a directory or not.

Create dir/notes on rightclick

---

electron/main/electron-store/ipcHandlers.ts
electron/main/electron-store/storeConfig.ts
src/components/Common/TitleBar.tsx
src/components/EmptyPage.tsx
src/components/File/NewNote.tsx
src/components/MainPage.tsx
src/components/Providers/TabProvider.tsx
src/components/Sidebars/IconsSidebar.tsx
src/components/Tabs/TabBar.tsx
src/utils/strings.ts

fix #352
/claim #352
This is a major refactor on how tabs work in app. Tabs now are decoupled from file path and can be either a file path and chat path. 
Some of the highlights from this implementations:
- tab can be file/chat;
- when a file tab is opened, file sidebar is also opened; when a chat tab is opened, chat sidebar is opened;
- when file/chat tabs are closed, their selected state is sidebar is also updated
https://github.com/user-attachments/assets/cabb9b79-bc7d-4891-8f78-15b102995f99

Refactor tab to work for both chat and file

---

src/components/Sidebars/FileSideBar/index.tsx

Closes #365.
Originally calculated height of sidebar by window.innerHeight, but never subtracted the height of the titlebar. Since it's fixed, we can just hardcode its height.

Fixed bottom note bug.

---

src/components/Editor/HighlightExtension.tsx

fix https://github.com/reorproject/reor/issues/348
/claim https://github.com/reorproject/reor/issues/348
I think it might be a product decision to show the highlight utility button when texts overflows, personally I think it would be better to display at the top but open for discussion
https://github.com/user-attachments/assets/65702027-fd01-4655-9772-cae98afde796

Always show highlight buttons

---

electron/main/llm/models/ollama.ts

chore: rename ollama exec file for linux

---

electron/main/llm/ipcHandlers.ts
electron/preload/index.ts
src/components/Settings/LLMSettings/DefaultLLMSelector.tsx
src/components/Settings/LLMSettings/hooks/use-llm-configs.ts

feat:delete ollama models

---

electron/main/electron-store/ipcHandlers.ts
electron/main/electron-store/storeConfig.ts
electron/preload/index.ts
src/components/WritingAssistant/ConversationHistory.tsx
src/components/WritingAssistant/WritingAssistant.tsx

fixes #441 
- Add checkbox to automatically include entire file content when no text is selected
- Store auto-context preference in electron-store        
- Fix undefined message error in currentConversation display
- Add proper type safety and null checks
- Update UI with clear labeling for auto-context feature
Evidence:
Updated:
https://github.com/user-attachments/assets/28ff5089-72e7-4d69-ae4a-392c5784cb33
Old:
https://github.com/user-attachments/assets/c8848edf-d89f-40bc-b0c3-bcf50c07ecbe
/claim #441

Feat   441  writing assistant checkbox for feeding current editor contents to llm

---

src/components/Settings/EmbeddingSettings/EmbeddingModelSelect.tsx

Fallback for embeddings that don't have `readableName` and `description` attributes.
Before:
After:

Fix: embedding models not showing in the dropdown

---

src/components/WritingAssistant/WritingAssistant.tsx

Fix the below scenarios, the trigger becomes invisible

fix: prevent writing assistant's trigger from being invisible

---

src/components/WritingAssistant/ConversationHistory.tsx
src/components/WritingAssistant/WritingAssistant.tsx

fix: match size with the output

---

.tamagui/tamagui-components.config.cjs
electron-builder.json5
package-lock.json
package.json
src/lib/blocknote/react/SideMenu/components/SideMenuPositioner.tsx
vite.config.mts

- Fixed small `zIndex` error on `SideMenuPositioner` that allowed it to display above a `Dialog`.
- Fixed build issue that was causing errors on macOS.

Fixed build issues with small zIndex change.

---

package-lock.json
src/lib/blocknote/core/BlockNoteExtensions.ts
src/lib/blocknote/core/extensions/Markdown/MarkdownExtension.ts

Fixed a bug on pasting non-media content. Originally, would not paste content but now it does.

Fix pasting
